WIP - fix(#1711) try to get workspace typescript with the tsdk path (yarn@berry compat)
vuejs/vetur pull request #1737
Opened 2020-02-28 16:15 UTC by AlexandreBonaventure

Naive attempt (proof of concept) to fetch TS runtime based on the `vscode.typescript.tsdk` setting with a fallback to `node_modules`. This will allow to use yarn@berry patched TS runtime as stated in #1711
I'd like to get some feedback/help to finalize this PR

2020-02-28 16:16 UTC, AlexandreBonaventure commented on server/src/services/vls.ts
> +    await this.dependencyService.init(workspacePath, config.vetur.useWorkspaceDependencies, config.typescript.tsdk);
I have no idea how to cleanly get the vscode `typescript.tsdk` setting. So this is really a guess, not tested obviously.

2020-02-28 16:17 UTC, AlexandreBonaventure commented on server/src/services/dependencyService.ts
> +      const workspaceTSPath = path.resolve(workspacePath, tsSDKPath || 'node_modules/typescript');
Not sure if this kind of fallback actually works. We would have to know what is the default value of the `typescript.tsdk` setting

2020-02-29 11:57 UTC, sbresin commented on server/src/services/dependencyService.ts
> +      const workspaceTSPath = path.resolve(workspacePath, tsSDKPath || 'node_modules/typescript');
The `typescript.tsdk` setting points directly to the `lib` folder, while we need to point to the parent to do `import(workspaceTSPath)`. This change makes it work.
If the `typescript.tsdk` is unset it defaults to `null`. So this would fallback to the old behaviour and try to load typescript from `node_modules/typescript`.

```suggestion
      const tsPath = tsSDKPath && path.join(tsSDKPath, '..');
      const workspaceTSPath = path.resolve(workspacePath, tsPath || 'node_modules/typescript');
```

2020-02-29 11:57 UTC, sbresin commented
hello. i have tested your changes and it's not working as it is. i added a comment how to make it work.

Additionaly, this doesn't work alone. While `yarn pnpify --sdk` sets up `.yarn/pnpify/typescript/lib/tsc.js` and `.yarn/pnpify/typescript/lib/tsserver.js` for us. In this case we also need `.yarn/pnpify/typescript/lib/typescript.js` with this content: 
```
#!/usr/bin/env node

const {createRequire, createRequireFromPath} = require(`module`);
const {resolve} = require(`path`);

const relPnpApiPath = "../../../../.pnp.js";

const absPnpApiPath = resolve(__dirname, relPnpApiPath);
const absRequire = (createRequire || createRequireFromPath)(absPnpApiPath);

// Setup the environment to be able to require typescript/lib/typescript.js
require(absPnpApiPath).setup();

// Defer to the real typescript/lib/typescript.js your application uses
module.exports = absRequire(`typescript/lib/typescript.js`);

```

this could easily be added to `@yarnpkg/pnpify` with a one line change.

2020-03-02 15:25 UTC, AlexandreBonaventure commented
@sbresin sounds good! thank you

2020-04-02 15:55 UTC, merceyz commented
I haven't tested this but this line might be a potential issue https://github.com/vuejs/vetur/blob/29122dd4a796d93cc0c9a52c0d7bd9ff039a5a83/server/src/modes/template/tagProviders/index.ts#L120

2020-07-06 04:35 UTC, yoyo930021 commented
Fixed #1996

2020-08-25 07:08 UTC, octref requested changes

2020-08-25 07:08 UTC, octref commented on server/src/services/vls.ts
> +    await this.dependencyService.init(workspacePath, config.vetur.useWorkspaceDependencies, config.typescript.tsdk);
The only issue is this doesn't handle such global settings:

```json
{
  "typescript.tsdk": "/usr/local/lib/node_modules/typescript/lib"
}
```

As seen in https://code.visualstudio.com/docs/typescript/typescript-compiling#_using-newer-typescript-versions

2020-08-25 07:33 UTC, octref approved these changes

2020-08-25 07:33 UTC, octref commented
Now all good. I tested both workspace / global tsdk setting. @AlexandreBonaventure thanks for your work and sorry for late response.

2020-08-25 07:34 UTC, merged