Fix props validator
vuejs/vetur pull request #2241
Opened 2020-09-04 10:53 UTC by yoyo930021

Fixed #2236 #2237

2020-09-06 04:37 UTC, octref requested changes

2020-09-06 04:37 UTC, octref commented on server/src/modes/template/services/vuePropValidation.ts
> +function normalizeHtmlAttributeNameToKebabCase(attr: string, defaultModel: string) {
If this is `defaultModel`, don't name the othe attribute as `defaultModel`. It would confuse the reader.

2020-09-06 04:51 UTC, yoyo930021 commented on server/src/modes/template/services/vuePropValidation.ts
> +function normalizeHtmlAttributeNameToKebabCase(attr: string, defaultModel: string) {
`defaultModelAttr`?

2020-09-06 04:58 UTC, octref commented on server/src/modes/template/services/vuePropValidation.ts
> +function normalizeHtmlAttributeNameToKebabCase(attr: string, defaultModel: string) {
I think `boundToModel` makes more sense, as in `a prop that is bound to model`.

2020-09-06 04:59 UTC, octref commented on server/src/modes/template/services/vuePropValidation.ts
> +function normalizeHtmlAttributeNameToKebabCase(attr: string, defaultModel: string) {
And this one could be `modelProp`, as you are trying to figure out which prop is bound to model and passing its name in.

2020-09-06 05:02 UTC, octref commented on server/src/modes/template/services/vuePropValidation.ts
> +        definedProps.find(prop => prop.defaultModel)?.name ?? 'value'
I would write my logic here:

- If it's `v-model`, create a function such as `normalizeModelAttr` that takes in the `definedProps` and find it's normalized prop. You can make this function use `normalizeHtmlAttributeNameToKebabCase`.
- If it's not, use `normalizeHtmlAttributeNameToKebabCase` directly

Currently this function is overloaded with too many things. Make one function do one thing is better (and then compose them).

2020-09-06 05:03 UTC, octref requested changes

2020-09-06 05:03 UTC, octref commented on server/src/modes/template/services/vuePropValidation.ts
> +function normalizeHtmlAttributeNameToKebabCase(attr: string, defaultModel: string) {
See the other comment — I'd do the removing `.sync` logic here (or removing any modifiers), but I'd do the model part in another function: https://github.com/vuejs/vetur/pull/2241/files#r484022087

2020-09-06 08:57 UTC, octref commented
Sorry I didn't wait. I'm planning to make a release soon to address the folidng issue and this issue, so I made the changes myself.

2020-09-06 09:06 UTC, merged

2020-09-07 03:12 UTC, yoyo930021 commented on server/src/modes/template/services/vuePropValidation.ts
> +function normalizeHtmlAttributeNameToKebabCase(attr: string, defaultModel: string) {
Your variable name is really better.
I've learned, thanks.

2020-09-07 03:16 UTC, yoyo930021 commented on server/src/modes/template/services/vuePropValidation.ts
> +        definedProps.find(prop => prop.defaultModel)?.name ?? 'value'
I hesitated when I wrote this function,
but I'm writing this anyway.

I will send a PR to refactor it.