Stop computing outdated diagnostics with CancellationToken
vuejs/vetur pull request #2332
Opened 2020-09-26 15:13 UTC by yoyo930021

Fixed #1263 
Fix a part of #2192

2020-09-27 09:03 UTC, yoyo930021 commented
I think we can't forward that cancellation token to TS Server for completion.
I only find a cancelling TS server all response method.

2020-09-27 09:12 UTC, yoyo930021 commented on server/src/modes/script/javascript.ts
> +
Ref: https://github.com/microsoft/TypeScript/blob/88c24e6b0d0efb868088ed6da359ef55e6f1c6b6/src/services/services.ts#L1504

2020-10-09 11:02 UTC, yoyo930021 commented
When this PR merged:
- Replace `CLIEngine` to `Eslint` for eslint deprecated Node api.
- Add `getSuggestionDiagnostics` support. Like deprecated, unused.
- Add Fix all feature.

2020-10-17 11:02 UTC, yoyo930021 commented
This PR is broken VTI diagnostic.
I need more research.

2020-10-17 12:02 UTC, yoyo930021 commented
I made a retarded mistake, and I've fixed it.

2020-10-29 13:12 UTC, octref requested changes

2020-10-29 13:12 UTC, octref commented on server/src/utils/cancellationToken.ts
> +    const Exception = this.tsModule.OperationCanceledException;
Do we have to do this assignment + TSLint rule?

2020-10-29 13:12 UTC, octref commented on server/src/services/vls.ts
> +        return this.doValidate(doc).then(result => result ?? []);
Make this callback async for readability

2020-10-29 13:12 UTC, octref commented on server/src/utils/cancellationToken.ts
> +export function isVCancellationTokenCancel(token?: VCancellationToken) {
Maybe call this `isVCancellationRequested` (or `isVCancellationRequestedOnToken` if you prefer)?

2020-10-29 13:12 UTC, octref commented on server/src/modes/script/javascript.ts
> +      if (!!(compilerOptions.declaration || compilerOptions.composite)) {
If the result is undefined this block won't execute, so I think it's unnecessary convert it to Boolean.

2020-10-29 13:22 UTC, yoyo930021 commented on server/src/modes/script/javascript.ts
> +      if (!!(compilerOptions.declaration || compilerOptions.composite)) {
I remember it is resolve type error.

2020-10-29 13:23 UTC, yoyo930021 commented on server/src/utils/cancellationToken.ts
> +export function isVCancellationTokenCancel(token?: VCancellationToken) {
`isVCancellationRequested` is great.

2020-10-29 13:26 UTC, yoyo930021 commented on server/src/utils/cancellationToken.ts
> +    const Exception = this.tsModule.OperationCanceledException;
This should be my mistake.
I read the tslint rules wrong.

2020-10-29 13:28 UTC, yoyo930021 commented on server/src/services/vls.ts
> +        return this.doValidate(doc).then(result => result ?? []);
Example add `async` in function?

2020-10-30 01:43 UTC, octref approved these changes

2020-10-30 01:43 UTC, merged