Add Vetur config file RFC
vuejs/vetur pull request #2378
Opened 2020-10-14 14:09 UTC by yoyo930021

Vetur configuration file.

[Rendered](https://github.com/vuejs/vetur/blob/vetur-config-file-rfc/rfcs/001-vetur-config-file.md)

2020-10-14 14:46 UTC, victorgarciaesgi commented
This is really great!

I have nothing to comment at the moment, everything seems ideal (I don't use monorepos thought so I can't debate on this)

2020-10-15 09:34 UTC, IlCallo commented
> Put configuration to `vue.config.js`

I'd exclude this alternative, as there are other CLIs (Nuxt, Quasar, etc) which needs Vetur

Into "properties details > definition" you use `monorepos` property name instead of `repos`

Have you checked other frameworks config files for tasks similar to this? Angular/React/whatever? If yes, is it possible to have link to relevant resources/inspiration?

2020-10-15 10:35 UTC, yoyo930021 commented
> > Put configuration to `vue.config.js`
> 
> I'd exclude this alternative, as there are other CLIs (Nuxt, Quasar, etc) which needs Vetur
> 
> Into "properties details > definition" you use `monorepos` property name instead of `repos`
> 
> Have you checked other frameworks config files for tasks similar to this? Angular/React/whatever? If yes, is it possible to have link to relevant resources/inspiration?

Thanks.
I fixed wrong text in RFC.

My first inspiration came from `svelte.config.js`.
https://github.com/sveltejs/svelte/issues/1101 https://github.com/sveltejs/language-tools/blob/3139ccd5b4306a914be4ba64b0c036fcd8888f78/packages/svelte-vscode/README.md#generic-setup
The Svelte VScode extension read this file.
But they don't really have the support of monorepo.

The React and Angular are all officially supported by TypeScript for monorepo support.
They are all based on TypeScript program `tsconfig.json`,
And they don't have their own unique files to deal with.
PS. TypeScript is direct support for `jsx`.

2020-10-15 13:31 UTC, yoyo930021 commented
I extend `repos[].globallyComponents` in RFC.
More consideration for customizable component names.

2020-10-19 20:31 UTC, andrewisaburden commented
Grammar for `globallyComponents` is not correct; perhaps `globalComponents` or `globallyRegisteredComponents`?

2020-10-21 12:41 UTC, yoyo930021 commented
> Grammar for `globallyComponents` is not correct; perhaps `globalComponents` or `globallyRegisteredComponents`?

I rename to `globalComponents`.

2020-10-24 07:20 UTC, antfu commented
`globalComponents` will help a lot to me! Really looking forward to this RFC get implemented! 👍

2020-10-24 07:20 UTC, znck commented on rfcs/001-vetur-config-file.md
> +  repos?: Array<{
`repos` is more connected to git repositories, and I get it, it's coming from monorepos but I feel it's not conveying the purpose.

Suggestion: We can call it `projects`.  (typescript has project references and that makes it some what similar)

2020-10-24 07:20 UTC, znck commented on rfcs/001-vetur-config-file.md
> +    globalComponents?: Array<Glob | { name: string, path: string }>
How about `"extends"` option to share configurations?

e.g.
```js
module.export = {
  projects: [{
    extends: ["vuetify"],
    globalComponents: ["./src/components/**/*.vue"]
  }]
}
```

2020-10-24 07:20 UTC, znck commented on rfcs/001-vetur-config-file.md
> +- Use pure JavaScript.
What is the reason for choosing `.js` over `.json`?

2020-10-24 07:21 UTC, antfu commented on rfcs/001-vetur-config-file.md
> +  repos?: Array<{
Maybe workspaces?

2020-10-24 07:30 UTC, yoyo930021 commented on rfcs/001-vetur-config-file.md
> +  repos?: Array<{
I agree. `projects` is better.

2020-10-24 07:35 UTC, yoyo930021 commented on rfcs/001-vetur-config-file.md
> +    globalComponents?: Array<Glob | { name: string, path: string }>
I don't understand what this setting means.
I think if we're going to share configurations, we can only use JS. Like `require`.

PS. When you use `vuetify` on package.json, we use component date to completion.
So you don't really need to define `vuetify` here!

2020-10-24 07:38 UTC, yoyo930021 commented on rfcs/001-vetur-config-file.md
> +- Use pure JavaScript.
Native JSON does not support commenting.
If you want to share your settings, you can use the JS mechanism directly.
Even if you want to support plugins in the distant future, this format will be easier to handle.

2020-10-24 09:44 UTC, sqal commented on rfcs/001-vetur-config-file.md
> +  repos?: Array<{
I like the "workspaces" name or maybe workingDirectories (stolen from eslint extension 😜)

2020-10-24 09:57 UTC, znck commented on rfcs/001-vetur-config-file.md
> +    globalComponents?: Array<Glob | { name: string, path: string }>
Similar to tsconfig but it doesn't makes sense in cjs.

2020-10-24 12:09 UTC, znck commented on rfcs/001-vetur-config-file.md
> +  repos?: Array<{
workspaces also sounds good as package managers have those.

2020-10-26 02:31 UTC, yoyo930021 commented on rfcs/001-vetur-config-file.md
> +  repos?: Array<{
The `workspaces` word is also used for multi roots in VSCode.
It's a bit confusing.

2020-10-31 10:31 UTC, octref commented on rfcs/001-vetur-config-file.md
> +  repos?: Array<{
As long as it's clear what it meant, it's ok, so +1 for projects.

2020-10-31 10:34 UTC, octref commented on rfcs/001-vetur-config-file.md
> +    globalComponents?: Array<Glob | { name: string, path: string }>
@znck I don't feel we need this. When you have:
- `vuetify` listed in pointed package.json's dependencies
- `node_modules/vuetify/package.json` has `vetur` key

Everything should work from there.

Unless you meant something else.

2020-10-31 10:47 UTC, znck commented on rfcs/001-vetur-config-file.md
> +    globalComponents?: Array<Glob | { name: string, path: string }>
We need to support opt-in for external global components. (user can register, only a few components)

2020-10-31 13:10 UTC, octref requested changes
LGTM, except 2 small things:

- `repos` -> `projects`
- Allow `projects` to be an array of either the shortform (just a string pointing to `root`) or the longer form (`root/package/tsconfig/globalComponents`).

2020-10-31 13:10 UTC, octref commented on rfcs/001-vetur-config-file.md
> +      globalComponents: [
Probably optional here? No value = `[]`.

2020-10-31 13:10 UTC, octref commented on rfcs/001-vetur-config-file.md
> +  repos?: Array<{
Probably also allow a shorthand form, so

```ts
Array<string | {
    root: string,
    package?: string,
    tsconfig?: string,
    globalComponents?: Array<Glob | { name: string, path: string }
>
```

Where `string` value is `root`.

2020-10-31 13:10 UTC, octref commented on rfcs/001-vetur-config-file.md
> +    globalComponents?: Array<Glob | { name: string, path: string }>
@znck What's a use case for that? If I understand you correctly, do you mean for the case when you have 2 UI lib and only want auto-completion for one of them (or only a few components out of a full library)? I feel there isn't much downside to just registering a whole library.

2020-10-31 13:14 UTC, znck commented on rfcs/001-vetur-config-file.md
> +    globalComponents?: Array<Glob | { name: string, path: string }>
Mainly for type checking global components.

2020-11-02 05:52 UTC, yoyo930021 commented on rfcs/001-vetur-config-file.md
> +  repos?: Array<{
It's a good idea.
I changed the RFC.

2020-11-02 05:53 UTC, yoyo930021 commented on rfcs/001-vetur-config-file.md
> +      globalComponents: [
It's a error.
I fix it.

2020-11-02 05:54 UTC, yoyo930021 commented on rfcs/001-vetur-config-file.md
> +    globalComponents?: Array<Glob | { name: string, path: string }>
I would prefer to use cjs directly.

module.export = {
  projects: [{
    globalComponents: [
      ...require('vuetify').components,
      "./src/components/**/*.vue"
    ]
  }]
}

2020-11-02 06:01 UTC, yoyo930021 commented on rfcs/001-vetur-config-file.md
> +    globalComponents?: Array<Glob | { name: string, path: string }>
I also think there's no point in adding an external lib.
We don't know the details of external libs.
It may be difficult to get the correct TypeScript type when no correct `tsconfig.json`.

2020-11-02 11:51 UTC, octref approved these changes
LGTM, thanks for addressing the feedback.

2020-11-02 13:02 UTC, znck commented on rfcs/001-vetur-config-file.md
> +    globalComponents?: Array<Glob | { name: string, path: string }>
In the TS plugin, I am using [this](https://github.com/znck/vue-developer-experience/blob/fb9655dfcb4b24a015e1dae76e1df14b241b6d0b/packages/analyze/src/component.ts#L83-L89) to infer component meta. (It has a different structure compared to vetur's spec but includes verbose static information).

2020-11-20 02:30 UTC, znck commented
How would named component from external module work?

```js
important { Foo } from 'foo'

app.component('MyFoo', Foo)
```

2020-11-20 02:51 UTC, yoyo930021 commented
> How would named component from external module work?
> 
> ```js
> important { Foo } from 'foo'
> 
> app.component('MyFoo', Foo)
> ```

This RFC don't solves the problem.
Vetur currently uses component data to do this.
In the long run, we need a type-based mechanism.
I think we can discuss a new RFC about this.

2020-11-20 02:52 UTC, znck commented
In the TS plugin, I am using the following data structure for the project config.

```ts
export interface ImportSource {
  moduleName: string
  exportName?: string
}

export interface ProjectConfig {
  root: string
  package?: string
  tsconfig?: string
  globalComponents: Array<string | Record<string, string | ImportSource>>
}
```

2020-11-20 02:55 UTC, znck commented
What is the purpose of `tsconfig` option?

2020-11-20 02:57 UTC, yoyo930021 commented
> In the TS plugin, I am using the following data structure for the project config.
> 
> ```ts
> export interface ImportSource {
>   moduleName: string
>   exportName?: string
> }
> 
> export interface ProjectConfig {
>   root: string
>   package?: string
>   tsconfig?: string
>   globalComponents: Array<string | Record<string, string | ImportSource>>
> }
> ```

I think we can keep it that way for now.
If vetur introduces such an approach, it will have to face the problem of historical component data.

2020-11-20 02:58 UTC, yoyo930021 commented
> What is the purpose of `tsconfig` option?

The vetur will use this option file to open the ts language service.

2020-11-20 03:27 UTC, znck commented
TS Plugin can only use `globalComponents`, everything else is inherited from the TypeScript project.

2020-11-20 03:30 UTC, yoyo930021 commented
> TS Plugin can only use `globalComponents`, everything else is inherited from the TypeScript project.

You may also want to refer to the `package`.
It can be used to know the Vue version of the project.
What external libraries are used?

2020-12-08 13:26 UTC, merged

2020-12-09 06:30 UTC, Lanseria commented
Can you set the vetur version here, so that accidental upgrades don't cause problems?

2020-12-09 06:33 UTC, yoyo930021 commented
> Can you set the vetur version here, so that accidental upgrades don't cause problems?

It's practically impossible.
You only can use `vetur.dev.vlsPath` option to pin vls version.