Fix/2430 sync modifier prop type checking
vuejs/vetur pull request #2431
Opened 2020-11-03 01:39 UTC by andrewisaburden

Fixes #2430

2020-11-08 15:08 UTC, yoyo930021 requested changes

2020-11-08 15:08 UTC, yoyo930021 commented on server/src/services/typescriptService/transformTemplate.ts
> +          dir.key.modifiers.length === 0 || !isVOn(dir)
I think `&& isVBind(dir)` more intuitive.

2020-11-08 19:58 UTC, andrewisaburden commented on server/src/services/typescriptService/transformTemplate.ts
> +          dir.key.modifiers.length === 0 || !isVOn(dir)
@yoyo930021 I agree, and initially that's what I did. However, for reasons that are not clear to me, using `isVBind` with the typeguard of `: node is AST.VDirective` results in line 256 throwing this TypeScript error: `Property 'key' does not exist on type 'never'.` for the section `...dir.key.modifiers.map`.

This doesn't make sense to me, because `dir` is already of type `AST.VDirective` in the function parameters. I couldn't figure out a solution, if you know one please let me know.

2020-11-08 20:29 UTC, andrewisaburden commented on server/src/services/typescriptService/transformTemplate.ts
> +          dir.key.modifiers.length === 0 || !isVOn(dir)
After reading a little more, typeguards that are type predicates *only* do one thing: confirm the type is guarded.

`isVBind` actually should be split into two methods, one for `isVDirective` and one for `isVBind`. `isVDirective` should be a type guard, e.g. `function isVDirective(node: AST.VAttribute | AST.VDirective): node is AST.VDirective {`
and `isVBind` should not be a type guard: `function isVBind(node: AST.VAttribute | AST.VDirective): boolean {`

2020-11-09 02:28 UTC, yoyo930021 approved these changes

2020-11-09 02:30 UTC, yoyo930021 commented
@ktsn If you have time, you can take a look.
I think I'll merge first. If you have any questions, let me know.

2020-11-09 12:12 UTC, merged