feat: add Yarn PnP support
vuejs/vetur pull request #2478
Opened 2020-11-16 14:50 UTC by merceyz

**What's the problem this PR addresses?**

Fixes https://github.com/vuejs/vetur/issues/2469
Fixes https://github.com/vuejs/vetur/issues/2092

**How did you fix it?**

- Use require.resolve to locate tag providers
- Setup the PnP hook from the workspace if it exists

2020-11-16 14:50 UTC, merceyz commented
Would it be fine if I changed https://github.com/vuejs/vetur/commit/e88c26b3f5e02ad42c2d49b2eb06eafdb86218dd to use `require.resolve` instead?

2020-11-17 04:22 UTC, yoyo930021 commented
> Would it be fine if I changed
> 
> https://github.com/vuejs/vetur/blob/03a4373ffb7cae8e07d313a886b1a72a386799f3/server%2Fsrc%2Fservices%2FdependencyService.ts#L165
> to use `require.resolve` instead?
> I guess that is supposed to half support workspaces, but at that point it should just run `require.resolve` in each workspace

I want to establish a dependency relationship in advance.
But I thought maybe in pnp it was redundant?

2020-12-01 09:42 UTC, merceyz commented
I'll omit that part for now, this makes the tag providers work under PnP

2020-12-01 09:47 UTC, yoyo930021 requested changes

2020-12-01 09:47 UTC, yoyo930021 commented on server/src/modes/template/tagProviders/externalTagProviders.ts
> +  const tagsPath = findConfigFile(
Do we need this function when we use `require.resolve` function?

2020-12-01 09:47 UTC, yoyo930021 commented on server/src/services/typescriptService/vueVersion.ts
>        nodeModulesVuePackagePath && JSON.parse(readFileSync(nodeModulesVuePackagePath, { encoding: 'utf-8' })!);
Do we need to replace `readFileSync` to `require`?

2020-12-01 09:50 UTC, merceyz commented on server/src/services/typescriptService/vueVersion.ts
>        nodeModulesVuePackagePath && JSON.parse(readFileSync(nodeModulesVuePackagePath, { encoding: 'utf-8' })!);
We don't have to since the full that is resolved right above, probably shouldn't as well since `require` will cache the result so any changes wont be noticed without restarting VSCode

2020-12-01 09:52 UTC, merceyz commented on server/src/modes/template/tagProviders/externalTagProviders.ts
> +  const tagsPath = findConfigFile(
I don't think it's needed here, no

2020-12-01 09:57 UTC, yoyo930021 commented on server/src/modes/template/tagProviders/externalTagProviders.ts
> +  const tagsPath = findConfigFile(
We can remove `findConfigFile`.

2020-12-01 10:00 UTC, yoyo930021 commented on server/src/services/typescriptService/vueVersion.ts
>        nodeModulesVuePackagePath && JSON.parse(readFileSync(nodeModulesVuePackagePath, { encoding: 'utf-8' })!);
What is `require.resolve` result when in pnp mode?
Can it be read directly?

2020-12-01 10:13 UTC, merceyz commented on server/src/services/typescriptService/vueVersion.ts
>        nodeModulesVuePackagePath && JSON.parse(readFileSync(nodeModulesVuePackagePath, { encoding: 'utf-8' })!);
It's an absolute filepath that just so happens to be within a zip file, the PnP hook takes care of adding support for reading from them directly.

Example:
```
require.resolve('lodash');
-> 
/project/.yarn/cache/lodash-npm-4.17.20-c0db62021c-7.zip/node_modules/lodash/lodash.js
```

The only PnP specific thing is to setup the `.pnp.js` file, the rest is as normal

2020-12-01 10:28 UTC, yoyo930021 commented on server/src/services/typescriptService/vueVersion.ts
>        nodeModulesVuePackagePath && JSON.parse(readFileSync(nodeModulesVuePackagePath, { encoding: 'utf-8' })!);
Can `fs.readFileSync` function read file in a zip file?

2020-12-01 10:34 UTC, merceyz commented on server/src/services/typescriptService/vueVersion.ts
>        nodeModulesVuePackagePath && JSON.parse(readFileSync(nodeModulesVuePackagePath, { encoding: 'utf-8' })!);
Yes, as mentioned, the pnp hook adds support for it

> [...] within a zip file, the PnP hook takes care of adding support for reading from them

2020-12-01 10:42 UTC, yoyo930021 commented on server/src/services/vls.ts
> +    if (this.workspacePath && !process.versions.pnp && config.vetur.useWorkspaceDependencies) {
@merceyz The latest question is `.pnp.js` position.
We try to support monorepo in this [RFC](https://github.com/vuejs/vetur/blob/vetur-config-file-rfc/rfcs/001-vetur-config-file.md#projectspackage)
Where is `.pnp.js` file? Same as `package.json`?

2020-12-01 10:48 UTC, merceyz commented on server/src/services/vls.ts
> +    if (this.workspacePath && !process.versions.pnp && config.vetur.useWorkspaceDependencies) {
It's always at the project root

2020-12-01 10:52 UTC, yoyo930021 commented on server/src/services/vls.ts
> +    if (this.workspacePath && !process.versions.pnp && config.vetur.useWorkspaceDependencies) {
If I have a monorepo project,
- /
- package/project1
- package/project2
- package/project1

When I open `/`, I can get full support.
When I only open `package/project1`, It is broken.

2020-12-01 10:55 UTC, merceyz commented on server/src/services/vls.ts
> +    if (this.workspacePath && !process.versions.pnp && config.vetur.useWorkspaceDependencies) {
Correct, but that's usually how that works, it's the same for TypeScript for example

2020-12-01 10:57 UTC, yoyo930021 approved these changes
LGTM, I will merge when #2495 merged.

2020-12-07 03:43 UTC, yoyo930021 commented on server/src/services/vls.ts
> +    if (!process.versions.pnp) {
What time is this variable set?

2020-12-07 09:20 UTC, merceyz commented on server/src/services/vls.ts
> +    if (!process.versions.pnp) {
It's set by the `.pnp.js` file when `setup` is called

2020-12-08 13:28 UTC, merged