Custom event auto complete
vuejs/vetur pull request #2558
Opened 2020-12-11 11:28 UTC by sapphi-red

This PR implements custom event auto complete.

Obtains data from
```ts
emits: {
  foo: () => true,
}
```
and
```ts
emits: ['foo']
```
.

![image](https://user-images.githubusercontent.com/49056869/101898334-4a9da500-3bef-11eb-8e9c-928d3019b07d.png)

Validations are not implemented.

refs #2392

2020-12-13 07:42 UTC, yoyo930021 requested changes
We also miss type check in event.

Thanks for your PR.
We originally expected to change to a full type implementation.
But I think your implementation is perfect for the transition period.

2020-12-13 07:42 UTC, yoyo930021 commented on server/src/modes/script/componentInfo.ts
> +    return undefined;
Maybe we can support this.
https://github.com/kaorun343/vue-property-decorator#Emit

2020-12-13 17:05 UTC, sapphi-red commented
I added features below!

- type check
- `@Emit` support
  - If there is multiple `@Emit` with same emit name, it infers that it retuns the union type of those return type.
  - If emits option is set also, it will not collect info from `@Emit`.

2020-12-14 12:17 UTC, yoyo930021 requested changes
LGTM, but I need some time for test.
Thanks your help.

2020-12-14 12:17 UTC, yoyo930021 commented on server/src/modes/script/componentInfo.ts
> +    if (result.length === 0 || !onlyUseObjectResultIfExists) {
We can't `result.length === 0` condition.
Class component allow this.

2020-12-14 13:05 UTC, sapphi-red commented on server/src/modes/script/componentInfo.ts
> +    if (result.length === 0 || !onlyUseObjectResultIfExists) {
I thought when there is a component like below, it will never emit `'foo-bar'` even if `@Emit` is declared.
```ts
@Component({
  emits: {
    foo: () => true
  }
})
export default class A extends Vue {
  @Emit()
  foo () { return true }

  @Emit()
  fooBar () { return true }
}
```
But yes it was not.

How should I handle it when it has a same event name in both `@Emit` and `emits`?
Just override `@Emit` one with `emits` one?

2021-01-03 12:52 UTC, bissolli commented
It doesn't give us type hints on what is coming from the event right? I've trying to find a good way to add a typed event but couldn't get anywhere close to a complete solution!

Found this [very nice package](https://github.com/andrewvasilchuk/vue-typed-emit), but I think it's not supported by Vetur - in the component where you use the event, it's not able to recognize the payload of the event!

Is there any good solution for that?

2021-01-03 13:53 UTC, sapphi-red commented
How about using `emits` option? See https://github.com/vuejs/rfcs/blob/master/active-rfcs/0030-emits-option.md#type-inference.

2021-01-04 06:30 UTC, bissolli commented
> How about using `emits` option? See https://github.com/vuejs/rfcs/blob/master/active-rfcs/0030-emits-option.md#type-inference.
> This PR obtains type data from this.

If I want to use it only for typing purpose I would need only to return true, right?
Any guesses on how long this PR will take to merge?

```
const Foo = defineComponent({
  emits: {
    submit: (payload: { email: string; password: string }) => true
  },

  methods: {
    onSubmit() {
      this.$emit('submit', {
        email: 'foo@bar.com',
        password: 123 // Type error!
      })

      this.$emit('non-declared-event') // Type error!
    }
  }
})
```

Also I am not very familiar with VSCode extensions, is there a way to use you PR to test it out?

2021-01-04 07:28 UTC, yoyo930021 commented
> Also I am not very familiar with VSCode extensions, is there a way to use you PR to test it out?

https://github.com/vuejs/vetur/wiki/Developing-Language-Server-Features

2021-01-05 14:01 UTC, sapphi-red commented on server/src/modes/script/componentInfo.ts
> +    if (result.length === 0 || !onlyUseObjectResultIfExists) {
@yoyo930021 Do you have any opinions about the question above?

2021-01-07 12:37 UTC, yoyo930021 commented on server/src/modes/script/componentInfo.ts
> +    if (result.length === 0 || !onlyUseObjectResultIfExists) {
There should be no problem.

2021-01-07 13:10 UTC, yoyo930021 approved these changes

2021-01-07 13:11 UTC, yoyo930021 commented on server/src/modes/template/tagProviders/componentInfoTagProvider.ts
> +        attributes.push(genAttribute(e.name, 'event', { kind: 'markdown', value: e.documentation || '' }));
I find that I get a better experience without `@` char the beginning.
so I remove it.

2021-01-07 13:14 UTC, yoyo930021 commented
LGTM, I will merge it when weekend.

The transforming template logic is changed in this PR.
@ktsn @octref can read it when you have time.

2021-01-07 13:38 UTC, sapphi-red commented on server/src/modes/script/componentInfo.ts
> +    if (result.length === 0 || !onlyUseObjectResultIfExists) {
@yoyo930021 
```ts
@Component({
  emits: {
    foo: (a: string) => true
  }
})
export default class A extends Vue {
  @Emit()
  foo () { return 0 }
}
```
This is an example which the type of listener will differ by overriding.
From `emits` the type becomes `(a: string) => void`, but from `@Emit` the type becomes `(a: number) => void`.

Overriding `@Emit` one with `emits` one will adopt `(a: string) => void`.

2021-01-07 13:41 UTC, yoyo930021 commented on server/src/modes/script/componentInfo.ts
> +    if (result.length === 0 || !onlyUseObjectResultIfExists) {
Oh, it's a misunderstanding.
Your code is correct, so I don't change it.
You are right.

2021-01-07 13:44 UTC, sapphi-red commented on server/src/modes/script/componentInfo.ts
> +    if (result.length === 0 || !onlyUseObjectResultIfExists) {
I found vue-property-decorator does not support vue 3 for now and is going to deprecate `@Emit` (https://github.com/kaorun343/vue-property-decorator/issues/353).
I will change the test cases.

2021-01-07 14:04 UTC, sapphi-red commented
I fixed the test with class components with `@Options` since it was changed forVue 3.
Also added the test with property decorator with Vue 2.

2021-01-21 13:16 UTC, merged