Dont include used attributes in suggestions
vuejs/vetur pull request #2565
Opened 2020-12-13 17:54 UTC by sapphi-red

This PR removes used attributes from suggestions except

- it is `class` , because `:class` and `class` can coexist (same with `style`)
  - https://eslint.vuejs.org/rules/no-duplicate-attributes.html
- it is a event listener, because it is able to listen to same event by adding modifiers

2020-12-14 01:47 UTC, merceyz commented on server/src/modes/template/services/htmlCompletion.ts
> +    usedAttributes: string[],
This would be much better suited as a `Set<string>` for performance

2020-12-14 10:45 UTC, sapphi-red commented on server/src/modes/template/services/htmlCompletion.ts
> +    usedAttributes: string[],
Oh it should be, thank you!

2020-12-14 12:08 UTC, yoyo930021 requested changes

2020-12-14 12:08 UTC, yoyo930021 commented on server/src/modes/template/services/htmlCompletion.ts
> +  return attr.replace(/^(?:v-bind:|:)/, '').replace(/^v-on:/, '@');
You can also consider this function.
https://github.com/vuejs/vetur/blob/b7ca3965f6a60b6413c1550788958b01de40d45e/server/src/modes/template/services/vuePropValidation.ts#L89

2020-12-14 12:08 UTC, yoyo930021 commented on server/src/modes/template/services/htmlCompletion.ts
> +  function collectUsedAttributes(): Set<string> {
You don't need this function.
`node.attributeNames` can get it.
Just like this https://github.com/vuejs/vetur/blob/b7ca3965f6a60b6413c1550788958b01de40d45e/server/src/modes/template/services/vuePropValidation.ts#L50.

2020-12-14 12:08 UTC, yoyo930021 commented on .prettierignore
> +server/src/modes/template/test/completion.test.ts
Why do we need this?

2020-12-14 14:19 UTC, sapphi-red commented on .prettierignore
> +server/src/modes/template/test/completion.test.ts
Prettier breaks many lines by adding missing end tags and so on like this. (about 18 lines)
![image](https://user-images.githubusercontent.com/49056869/102091568-580e9580-3e62-11eb-8db6-594c51bca534.png)

Should I put `<!-- prettier-ignore -->` comments on every line?

2020-12-24 12:55 UTC, yoyo930021 approved these changes

2020-12-29 08:54 UTC, sapphi-red commented
I rewrote it with Set. I have forgotten about the previous comment... https://github.com/vuejs/vetur/pull/2565#discussion_r542059708

2021-01-21 13:13 UTC, merged