Update import on file rename
vuejs/vetur pull request #2651
Opened 2021-01-27 14:40 UTC by jasonlyu123

related to #820 
have to introduce some new API to `IScriptHost` and `ProjectService` because the request is not similar to the existing features. Haven't done the integration test Because I end up using the `applyEdit` request. I can't find a set of vscode API that can be used to test it. Maybe we can just test it in the server test?

Looking forward to feedbacks if anyone can found some strange behavior.

2021-02-03 07:59 UTC, jasonlyu123 commented
I see a [new confirm UI](https://github.com/microsoft/vscode-docs/blob/vnext/release-notes/v1_53.md#improved-refactor-participants-ui) in 1.53 insider. I think I can remove the custom confirmation. And we can wait until that was released and use the official confirmation instead.

2021-02-04 09:19 UTC, pakohan commented
Hey, I'm really looking forward, but never touched development of VSCode plugins. If it's helpful for you, could you tell me how to test this?

Again, thank you for this missing feature :-)

2021-02-04 09:31 UTC, jasonlyu123 commented
You can check out my branch and follow the doc [here](https://github.com/vuejs/vetur/wiki/Developing-Language-Server-Features#development). 
Following the debug step and you will see a debug vscode window pops up. Just open a folder and you can try it out. You can also use the vscode insider version to debug it. And you will see the confirmation I mentioned.

2021-02-06 02:29 UTC, w3bdesign approved these changes

2021-02-12 14:14 UTC, yoyo930021 commented
I'm so sorry about no immediate feedback provided.

I always thought there would be a conflict with VSCode typescript integration.
If you think there is nothing wrong with this, we can try to release it.

2021-02-12 14:44 UTC, yoyo930021 requested changes
Thanks for your help.

2021-02-12 14:44 UTC, yoyo930021 commented on server/src/modes/script/javascript.ts
> +        const doc = serviceHost.getScriptDoc(isWindows ? fileName.replace(/\//g, '\\') : fileName);
Why don't use `getSourceDoc`?
https://github.com/vuejs/vetur/blob/304e7567f11a709171a0ae987b115e9054907047/server/src/modes/script/javascript.ts#L911

2021-02-12 14:44 UTC, yoyo930021 commented on server/src/modes/script/javascript.ts
> +      const normalizedOldPath = oldPath.replace(/\\/g, '/');
Is this action required?

2021-02-12 14:44 UTC, yoyo930021 commented on server/src/modes/script/javascript.ts
> +      const edits = service.getEditsForFileRename(normalizedOldPath, normalizedNewPath, {}, {});
You can get perferences and formatSettings.
```
const formatSettings: ts.FormatCodeSettings = getFormatCodeSettings(env.getConfig());
const preferences = getUserPreferences(scriptDoc);
```

2021-02-12 14:44 UTC, yoyo930021 commented on server/src/services/typescriptService/serviceHost.ts
> +    getScriptDoc: (fileName: string) => localScriptRegionDocuments.get(fileName),
It is not necessary.

2021-02-12 14:44 UTC, yoyo930021 commented on server/src/services/vls.ts
> +    const inTheSameProject = files.filter(file => {
We can add `vetur.languageFeatures.updateImportOnFileMove === 'never'` logic.
This function can be turned off normally when there is a problem.

2021-02-13 01:33 UTC, jasonlyu123 commented on server/src/modes/script/javascript.ts
> +      const normalizedOldPath = oldPath.replace(/\\/g, '/');
Yes. Language service doesn't normalize the path here.

2021-02-13 01:35 UTC, jasonlyu123 commented on server/src/modes/script/javascript.ts
> +        const doc = serviceHost.getScriptDoc(isWindows ? fileName.replace(/\//g, '\\') : fileName);
I'm trying to get the version of the document.

2021-02-13 01:36 UTC, jasonlyu123 commented on server/src/modes/script/javascript.ts
> +      const edits = service.getEditsForFileRename(normalizedOldPath, normalizedNewPath, {}, {});
From my testing. It doesn't rewrite the import according to the preferences. But I can add it if you prefer.

2021-02-15 16:56 UTC, pakohan commented
Finally got the time to try it out. It works! I can't wait for the official release :-)

2021-02-17 01:42 UTC, jasonlyu123 commented on server/src/modes/script/javascript.ts
> +      const edits = service.getEditsForFileRename(normalizedOldPath, normalizedNewPath, {}, {});
This also needs the `getScriptDoc` I added. Because the request only has URI. And the version of the `TextDocument` is needed in `updateCurrentVueTextDocument` so we can't use that function.

2021-02-17 01:44 UTC, yoyo930021 commented on server/src/modes/script/javascript.ts
> +        const doc = serviceHost.getScriptDoc(isWindows ? fileName.replace(/\//g, '\\') : fileName);
This version isn't needed.

2021-02-17 01:45 UTC, yoyo930021 commented on server/src/modes/script/javascript.ts
> +      const edits = service.getEditsForFileRename(normalizedOldPath, normalizedNewPath, {}, {});
You can use `getSourceDoc` for replace it.

2021-02-17 01:50 UTC, yoyo930021 commented on server/src/modes/script/javascript.ts
> +      const normalizedOldPath = oldPath.replace(/\\/g, '/');
We don't need this logic in other features.

Maybe you need it when using `localScriptRegionDocuments.get` function?

2021-02-17 02:39 UTC, jasonlyu123 commented on server/src/modes/script/javascript.ts
> +        const doc = serviceHost.getScriptDoc(isWindows ? fileName.replace(/\//g, '\\') : fileName);
Version is for the client to determine if the update is outdated but it's not very important. I think I'll remove this.

2021-02-17 03:01 UTC, jasonlyu123 commented on server/src/modes/script/javascript.ts
> +      const normalizedOldPath = oldPath.replace(/\\/g, '/');
Typescript normally normalizes the path in `getSourceFile`. But this feature doesn't use that. Maybe this is a bug on their side. I'll add a comment here to explain it. If somehow they change the behavior later we can remove this.

2021-02-17 03:07 UTC, yoyo930021 commented on server/src/modes/script/javascript.ts
> +        const doc = serviceHost.getScriptDoc(isWindows ? fileName.replace(/\//g, '\\') : fileName);
If you judge it to be important, you need to use this function for get correct TextDocument.
https://github.com/vuejs/vetur/blob/8435ed3bb6cb70f5963b10238173a57d1dec2108/server/src/services/documentService.ts#L16

TypeScript language service isn't the same as language server protocol.
Their relationship is really troublesome. 😅

2021-02-17 03:09 UTC, yoyo930021 commented on server/src/modes/script/javascript.ts
> +      const normalizedOldPath = oldPath.replace(/\\/g, '/');
When using `getSourceDoc`, I think you'll be able to remove it.

2021-02-17 05:52 UTC, jasonlyu123 commented on test/lsp/features/renameFiles/basic.test.ts
> +        vscode.workspace.applyEdit(renameEdit).then(() => resolve());
Cleanup still doesn't work sometimes. Need to find the problem

2021-02-17 10:19 UTC, yoyo930021 commented on server/src/modes/script/javascript.ts
> +      const { scriptDoc } = updateCurrentVueTextDocument(sourceFileToSourceDoc(oldPath, sourceFile));
I think you don't need `updateCurrentVueTextDocument`.

2021-02-17 10:20 UTC, yoyo930021 commented on test/lsp/features/renameFiles/basic.test.ts
> +        vscode.workspace.applyEdit(renameEdit).then(() => resolve());
It does not seem to be a good way to test.
If unfortunately no solution is found, we can use `this.retries(3)`.

2021-02-18 04:23 UTC, jasonlyu123 commented on test/lsp/features/renameFiles/basic.test.ts
> +        vscode.workspace.applyEdit(renameEdit).then(() => resolve());
Another way I can think of is to use [extension.exports](https://code.visualstudio.com/api/references/vscode-api#extensions) to expose the `sendRequest` method of the language server client.
This method can also be used in other future features where we can't found a built-in command or a vscode API to test it. For example, the selection range.

2021-02-18 04:55 UTC, jasonlyu123 commented
> I always thought there would be a conflict with VSCode typescript integration.

About this maybe we can filter out all the edits to js and ts files?

2021-02-18 10:13 UTC, jasonlyu123 commented on server/src/modes/script/javascript.ts
> +      const { scriptDoc } = updateCurrentVueTextDocument(sourceFileToSourceDoc(oldPath, sourceFile));
Any alternative? We don't know the `languageId` of the text document here. That means all the user preferences would be for javascript.

2021-02-18 14:43 UTC, pakohan commented
I've checked out the latest commit and might be doing sth. wrong, but it's not working anymore:

```
Trace: TypeError: Cannot read property 'getProjectVersion' of undefined
    at synchronizeHostData (/Users/mogli/Desktop/vetur-update-import/server/node_modules/typescript/lib/typescript.js:147068:22)
    at getProgram (/Users/mogli/Desktop/vetur-update-import/server/node_modules/typescript/lib/typescript.js:147233:13)
    at Object.getEditsForFileRename (/Users/mogli/Desktop/vetur-update-import/server/node_modules/typescript/lib/typescript.js:147629:45)
    at Object.getRenameFileEdit (/Users/mogli/Desktop/vetur-update-import/server/dist/vls.js:674:4288)
    at Object.onWillRenameFile (/Users/mogli/Desktop/vetur-update-import/server/dist/vls.js:858:3433)
    at /Users/mogli/Desktop/vetur-update-import/server/dist/vls.js:858:16256
    at async Promise.all (index 0)
    at async GP.onWillRenameFiles (/Users/mogli/Desktop/vetur-update-import/server/dist/vls.js:858:16145)
    at Object.getRenameFileEdit (/Users/mogli/Desktop/vetur-update-import/server/dist/vls.js:674:4968)
    at Object.onWillRenameFile (/Users/mogli/Desktop/vetur-update-import/server/dist/vls.js:858:3433)
    at /Users/mogli/Desktop/vetur-update-import/server/dist/vls.js:858:16256
    at async Promise.all (index 0)
    at async GP.onWillRenameFiles (/Users/mogli/Desktop/vetur-update-import/server/dist/vls.js:858:16145)
```

2021-02-18 15:58 UTC, pakohan commented
btw, is there any way to stop the operation so that the file does not get moved?

2021-02-19 03:53 UTC, jasonlyu123 commented on test/lsp/features/renameFiles/basic.test.ts
> +        vscode.workspace.applyEdit(renameEdit).then(() => resolve());
Demo here https://github.com/jasonlyu123/vetur/commit/7acf8e9675c7e5847ad5e9d366653ebf3811286f. Found we can only expose it in testing.

2021-02-19 04:04 UTC, jasonlyu123 commented
> I've checked out the latest commit and might be doing sth. wrong, but it's not working anymore:
I can't reproduce this. Is it not working at all? or it's only in a specific situation? Also, I have pulled the latest commits of the master branch to resolve the merging conflict. You'll have to run yarn again.

> btw, is there any way to stop the operation so that the file does not get moved?
The confirm windows of vscode 1.53 have a skip option. it would skip all the edits. And you can undo rename file like a normal undo(Ctrl+Z).

2021-02-22 03:59 UTC, yoyo930021 commented on server/src/modes/script/javascript.ts
> +      const { scriptDoc } = updateCurrentVueTextDocument(sourceFileToSourceDoc(oldPath, sourceFile));
I think this is how it will be for now.

2021-02-22 04:00 UTC, yoyo930021 commented on test/lsp/features/renameFiles/basic.test.ts
> +        vscode.workspace.applyEdit(renameEdit).then(() => resolve());
I think we can do this first, no problem.

2021-02-26 10:13 UTC, yoyo930021 commented
> > I always thought there would be a conflict with VSCode typescript integration.
> 
> About this maybe we can filter out all the edits to js and ts files?

If the test is not a problem, perhaps we can observe.

2021-02-26 10:14 UTC, yoyo930021 approved these changes
LGTM, If no any question, I will merge it.

2021-02-26 15:18 UTC, jasonlyu123 commented
Can any check it for me? The new test I added works for me on windows. But I just can't figure out why it doesn't work on the Linux test. Open the `test/lsp/fixure` directory in debugging and move the `Basic.vue` into a new subfolder. Does it work?

2021-03-02 07:22 UTC, jasonlyu123 commented on server/src/modes/script/javascript.ts
> +        (sourceFile as any).scriptKind === tsModule.ScriptKind.JS ? 'javascript' : 'typescript'
Can't use `sourceFileToSourceDoc` or `getSourceDoc` here. It would treat the script content as a vue file. Thus it would get a default script content instead. It only works sometimes because of the caching.
I was hesitant about whether to use this typescript internal API or expose another `getScriptKind` function from `serviceHost`

2021-03-02 13:23 UTC, yoyo930021 commented on server/src/modes/script/javascript.ts
> +        (sourceFile as any).scriptKind === tsModule.ScriptKind.JS ? 'javascript' : 'typescript'
I'm guessing you mean `getLanguageModelCache`......
I also want to remove this cache.

I think we can keep the way you write for now.

2021-03-02 13:24 UTC, yoyo930021 commented on server/src/modes/script/javascript.ts
> +        (sourceFile as any).scriptKind === tsModule.ScriptKind.JS ? 'javascript' : 'typescript'
@jasonlyu123 If you don't have any problem, I will release it in new version.

2021-03-02 13:25 UTC, jasonlyu123 commented on server/src/modes/script/javascript.ts
> +        (sourceFile as any).scriptKind === tsModule.ScriptKind.JS ? 'javascript' : 'typescript'
ok!

2021-03-02 13:26 UTC, merged