add error-only option to vti diagnostics
vuejs/vetur pull request #2752
Opened 2021-03-03 04:21 UTC by Monchi

Resolves #2723.

`vti diagnostics --error-only` to ignore warns and print only errors.

```bash
$ vti diagnostics --help
Usage: vti diagnostics [options] [workspace]

Print all diagnostics

Options:
  -e, --error-only  Print only errors (default: false)
  -h, --help        display help for command

```

2021-03-05 11:33 UTC, yoyo930021 requested changes
Thank you.

2021-03-05 11:33 UTC, yoyo930021 commented on vti/src/cli.ts
> +      console.log(options);
we can remove it.

2021-03-05 11:33 UTC, yoyo930021 commented on vti/src/cli.ts
> +    .option('-e, --error-only', 'Print only errors', false)
The `DiagnosticSeverity` have four options.
Maybe we can make it a little more flexible.

2021-03-07 15:57 UTC, Monchi commented on vti/src/cli.ts
> +    .option('-e, --error-only', 'Print only errors', false)
@yoyo930021 I thought that the practical use case would be `--error-only` but flexibility is of course important. I've implemented `--log-level` option instead of `--error-only`.

BTW Currently `Information` and `Hint` severity would be printed as a warning. This is not in the scope of this PR and I would fix it in the other PR.

2021-03-08 12:40 UTC, yoyo930021 requested changes
LGTM

2021-03-08 12:40 UTC, yoyo930021 commented on vti/src/cli.ts
> +      if (
Why don't use `logLevels` from import?

2021-03-08 12:40 UTC, yoyo930021 commented on vti/src/commands/diagnostics.ts
> +  switch (logLevel) {
Maybe using map of JS object replace `switch...case`?

2021-03-08 13:51 UTC, Monchi commented on vti/src/cli.ts
> +      if (
@yoyo930021 Because `logLevels` type is `readonly ["ERROR", "WARN", "INFO", "HINT"]`, we cannot call `logLevels.includes` with unknown value.

related issue: https://github.com/microsoft/TypeScript/issues/26255

2021-03-08 13:51 UTC, Monchi commented on vti/src/commands/diagnostics.ts
> +  switch (logLevel) {
sounds good, thanks!

2021-03-08 14:47 UTC, yoyo930021 commented on vti/src/cli.ts
> +      if (
We can use `as` keyword or `is` function to force it.
Repeated text will cause follow-up maintenance problems.

2021-03-08 14:56 UTC, Monchi commented on vti/src/cli.ts
> +      if (
@yoyo930021 ok. I've removed repeated text. e905cb2

2021-03-08 15:02 UTC, yoyo930021 approved these changes

2021-03-08 15:02 UTC, merged