Semantic tokens for typescript
vuejs/vetur pull request #2802
Opened 2021-03-23 02:34 UTC by jasonlyu123

#1904 #2687
### implentation 

Add semantic token feature for script region. Due to typescript's implementation. It's currently not available for js. Also because of that, this is currently not available in interpolation mode. But I still left some merging strategy in the project service for potential future implementation. 

A couple of things like to discuss. 

1. There's some new built-in vscode command in [1.53](https://code.visualstudio.com/updates/v1_53#_semantic-token-commands)
Wondering if I should update the integration test to use it. The advantage is it's more integrated than a language-server request. And  I don't have to copy the semantic token legend to the test script. A disadvantage is we might accidentally ship features not compatible with 1.52.  

2. Computed member is highlighted as a method. Should we need to override it?

### screenshot
Here is some screenshot comparison. The theme is GitHub dark.
Without semantic tokens
![圖片](https://user-images.githubusercontent.com/36730922/112081287-620d0680-8bbe-11eb-9b52-250ef99244b7.png)

With semantic tokens
![圖片](https://user-images.githubusercontent.com/36730922/112081236-4a358280-8bbe-11eb-9c8f-4e33bab5d786.png)

Without 
![圖片](https://user-images.githubusercontent.com/36730922/112083866-cd58d780-8bc2-11eb-98a3-70c08a089968.png)

With
![圖片](https://user-images.githubusercontent.com/36730922/112083815-b1edcc80-8bc2-11eb-8445-5c7a9fbfd08c.png)

2021-03-23 12:26 UTC, yoyo930021 commented
> There's some new built-in vscode command in 1.53
Wondering if I should update the integration test to use it. The advantage is it's more integrated than a language-server request. And I don't have to copy the semantic token legend to the test script. A disadvantage is we might accidentally ship features not compatible with 1.52.

My understanding is that you can use them.
Testing theoretically does not affect users.

> Computed member is highlighted as a method. Should we need to override it?

Do you know what it looks like in a typescript file?

2021-03-24 01:07 UTC, jasonlyu123 commented
> My understanding is that you can use them.
Testing theoretically does not affect users.

Yes. It's just a very little chance that something doesn't work on an older version and we tested in a newer version so we didn't know. If you think it's ok I'll bump it.

>Do you know what it looks like in a typescript file? 
Should be the same as my current implementation. I haven't customized it. Because computed properties are method in the option object it has been highlighted as method not property.

2021-03-24 03:10 UTC, yoyo930021 commented
> Yes. It's just a very little chance that something doesn't work on an older version and we tested in a newer version so we didn't know. If you think it's ok I'll bump it.

You can bump vscode version in the test. 👍

> Should be the same as my current implementation. I haven't customized it. Because computed properties are method in the option object it has been highlighted as method not property.

If same, I think we can keep it. Get feedback after the release.
Consider doing it together with this https://github.com/vuejs/vetur/issues/2434 .

2021-03-24 10:11 UTC, jasonlyu123 commented
added #2434. Currently settle with a fallback TextMate scope of `entity.name.function`. If anyone can think of another better highlight scope, I can change it.

You can also customize the color follow [this doc](https://code.visualstudio.com/api/language-extensions/semantic-highlight-guide#theming) after it goes live.

2021-03-26 12:36 UTC, yoyo930021 commented
I will take a look on weekend.

2021-04-07 12:46 UTC, yoyo930021 requested changes
LGTM
Sorry for the late reply.

2021-04-07 12:46 UTC, yoyo930021 commented on server/src/services/vls.ts
> +    this.lspConnection.onRequest(SemanticTokensRangeRequest.type, this.onSemanticToken.bind(this));
Use `this.lspConnection.languages.semanticTokens.on` and `this.lspConnection.languages.semanticTokens.onRange` ?

2021-04-07 12:46 UTC, yoyo930021 commented on server/src/services/projectService.ts
> +          return null;
Why need this condition?
If some language broken, it probably disallows other languages.

2021-04-07 12:46 UTC, yoyo930021 commented on package.json
> +    ]
I also want to add this config.
```json
{
  "contributes": {
    "configurationDefaults": {
      "[vue]": {
        "editor.semanticTokenColorCustomizations": {
          "enabled": true,
          "rules": {
            "variable.ref": {
              "underline": true
            }
          }
        }
      }
    }
  }
}
```

2021-04-07 13:24 UTC, jasonlyu123 commented on server/src/services/vls.ts
> +    this.lspConnection.onRequest(SemanticTokensRangeRequest.type, this.onSemanticToken.bind(this));
The typing with that one doesn't allow a null result. But it's needed to disable full document semantic token for performance reason.

2021-04-07 13:33 UTC, jasonlyu123 commented on server/src/services/projectService.ts
> +          return null;
I prefer it doesn't have a partial result for one language. But if you prefer the opposite I can remove it.

2021-04-07 13:58 UTC, jasonlyu123 commented on package.json
> +    ]
umm... vscode show warning about unknown editor configuration. Also, what is this`variable.ref` rule?

2021-04-08 03:08 UTC, yoyo930021 commented on package.json
> +    ]
Oh, I only want to make `Ref` underline.
Use `property.refValue` in this case.

2021-04-08 03:10 UTC, jasonlyu123 commented on server/src/services/vls.ts
> +    this.lspConnection.onRequest(SemanticTokensRangeRequest.type, this.onSemanticToken.bind(this));
I changed it to always return an empty array when a file is too big. i.e. completely disable semantic highlight on big files. So we don't need null anymore.

2021-04-08 03:28 UTC, jasonlyu123 commented on package.json
> +    ]
Doesn't seems to work. Maybe this config is not in effect here

2021-04-08 12:48 UTC, yoyo930021 commented on package.json
> +    ]
No problem. I can try it.

2021-04-08 12:49 UTC, yoyo930021 approved these changes
LGTM

2021-04-08 12:51 UTC, merged