SugarSS Syntax Highlight
vuejs/vetur pull request #2828
Opened 2021-04-01 03:14 UTC by softwaredeveloptam

2021-04-07 12:11 UTC, yoyo930021 requested changes

2021-04-07 12:11 UTC, yoyo930021 commented on server/src/modes/style/index.ts
> +  const languageService = getCSSLanguageService();
If you use LSP, you need to add tests.
Replace `getSCSSLanguageService` to `getCSSLanguageService`?
https://github.com/MhMadHamster/vscode-postcss-language/blob/f2e7ff3be4d112fd22e4b5f43068a27c92652410/server/src/postcssServerMain.ts#L65

2021-04-11 16:55 UTC, octref reviewed
https://github.com/hudochenkov/Syntax-highlighting-for-PostCSS/tree/master/Syntaxes Not sure if this is a better one, as it's more popular.

2021-04-11 16:55 UTC, octref commented on server/src/modes/style/index.ts
> +  const languageService = getCSSLanguageService();
Is using SCSS language service to support sugarss a good idea at all? As far as I know SCSS is not a superset of SugarSS. I think we should only support highlighting for SugarSS at most.

2021-04-15 04:00 UTC, softwaredeveloptam commented on server/src/modes/style/index.ts
> +  const languageService = getCSSLanguageService();
I spoke with @yoyo930021 a bit over Discord and it seems that SCSS/CSS language service aren't the best for SugarSS LSP. I've removed the LSP for now and will make another PR (or might have to create a `SugarSSLanguageService` then integrate it to future PR for Vetur)

2021-04-15 04:11 UTC, softwaredeveloptam commented
> https://github.com/hudochenkov/Syntax-highlighting-for-PostCSS/tree/master/Syntaxes Not sure if this is a better one, as it's more popular.

Both [hudochenkov's Syntax Highlighting for PostCSS](https://github.com/hudochenkov/Syntax-highlighting-for-PostCSS) and [aazcast's Syntax SugarSS SublimeText](https://github.com/aazcast/Syntax-SugarSS-SublimeText) have very similar grammar. [SugarSS](https://github.com/postcss/sugarss#text-editors) expresses that aazcast's SugarSS plugin is the go-to for SugarSS in Sublime 🙏. I hope this integration would be okay for Vetur 👍 . Very grateful for the chance to contribute to such a big resource to the Vue community 🙏 .

2021-04-26 11:25 UTC, yoyo930021 approved these changes
LGTM

2021-04-26 11:26 UTC, merged