look for a .stylintrc file when formatting stylus code
vuejs/vetur pull request #2863
Opened 2021-04-13 08:56 UTC by ntraut

For issue #2689.

2021-04-26 11:23 UTC, yoyo930021 commented on server/src/modes/style/stylus/index.ts
> +      const stylintrcPath = path.join(env.getRootPathForConfig(), '.stylintrc');
Maybe use `env.getProjectRoot()` ?

2021-04-26 11:24 UTC, yoyo930021 requested changes
LGTM, only a little problem.

2021-05-05 22:03 UTC, ntraut commented on server/src/modes/style/stylus/index.ts
> +      const stylintrcPath = path.join(env.getRootPathForConfig(), '.stylintrc');
Changed. `env.getProjectRoot()` gives me the same result as `env.getRootPathForConfig()`.

2021-05-11 01:43 UTC, yoyo930021 commented on server/src/modes/style/stylus/index.ts
> +      const stylintrcPath = path.join(env.getRootPathForConfig(), '.stylintrc');
They are sometimes different.

2021-05-11 01:44 UTC, yoyo930021 approved these changes

2021-05-11 01:46 UTC, merged